### ISSUE TITLE
RuntimeError: No CUDA GPUs are available when annotations executed

### ISSUE THREAD

**Issue by burgosmad** [Yuqifan1117/Annotation-anything-pipeline#5]
Hi, Im trying to run the code but, when running _bash annotation.sh_ it is showing **RuntimeError: No CUDA GPUs are available.** However, when I check if thats true it doesnt seem to coincide.  Any idea?

`Python 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())
True
>>> print(torch.cuda.get_device_name())
Quadro RTX 4000
>>> print(torch.__version__)
1.13.0
>>> print(torch.version.cuda)
11.7
>>> x=torch.rand(1).cuda()
>>> print(x)
tensor([0.9740], device='cuda:0')
>>> x=torch.rand(1).to("cuda")
>>> print(x)
tensor([0.5562], device='cuda:0')
>>> torch._C._cuda_init()
`

The RunTime Error is:
**(LAP) a0621@a0621:/media/a0621/HDD1T/Labal-Anything-Pipeline$ bash annotation.sh 
/home/a0621/anaconda3/envs/LAP/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1666642969563/work/aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
final text_encoder_type: bert-base-uncased
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
_IncompatibleKeys(missing_keys=[], unexpected_keys=['label_enc.weight'])
Traceback (most recent call last):
  File "/media/a0621/HDD1T/Labal-Anything-Pipeline/grounded_sam.py", line 225, in <module>
    blip_model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-large", torch_dtype=torch.float16).to("cuda")
  File "/home/a0621/anaconda3/envs/LAP/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1896, in to
    return super().to(*args, **kwargs)
  File "/home/a0621/anaconda3/envs/LAP/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in to
    return self._apply(convert)
  File "/home/a0621/anaconda3/envs/LAP/lib/python3.10/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/home/a0621/anaconda3/envs/LAP/lib/python3.10/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/home/a0621/anaconda3/envs/LAP/lib/python3.10/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/home/a0621/anaconda3/envs/LAP/lib/python3.10/site-packages/torch/nn/modules/module.py", line 662, in _apply
    param_applied = fn(param)
  File "/home/a0621/anaconda3/envs/LAP/lib/python3.10/site-packages/torch/nn/modules/module.py", line 985, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/a0621/anaconda3/envs/LAP/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available**

**Comment by Yuqifan1117** [comment]
Because you only have one cuda in your environment, however I use ``export CUDA_VISIBLE_DEVICES=1`` in the bash. You can set the ``export CUDA_VISIBLE_DEVICES=0`` instead of ``export CUDA_VISIBLE_DEVICES=1``.

**Comment by burgosmad** [comment]
Thank you very much!
